### ISSUE TITLE
show area of recording

### ISSUE THREAD

**Issue by r4pr0n** [ammen99/wf-recorder#146]
it would be nice if wf-recorder could show the border of the area where wf-recorder is recording

**Comment by ammen99** [comment]
I consider this out of scope for the project, it would require GUI work.

**Comment by soreau** [comment]
Client-side gui rendering from wf-recorder doesn't really make sense because the border would end up in the recording without special compositor support. IMO it would probably make more sense to do this in the compositor. After a frame is complete, send the bits to wf-recorder and then render the border before displaying the frame, so the border doesn't show in the recording.

**Comment by ammen99** [comment]
> Client-side gui rendering from wf-recorder doesn't really make sense because the border would end up in the recording without special compositor support. IMO it would probably make more sense to do this in the compositor. After a frame is complete, send the bits to wf-recorder and then render the border before displaying the frame, so the border doesn't show in the recording.

we could, in theory, make it so that the border is just outside of the recorded region. However, it all depends on how you want it to look like, if we want a visual indication even for ex. for full screen recording, we're out of luck without compositor support as you said.

**Comment by r4pr0n** [comment]
I get that, I just thought that it might be inside the scope, since you can do that if you use ffmpeg with x11grab

**Comment by ammen99** [comment]
> I get that, I just thought that it might be inside the scope, since you can do that if you use ffmpeg with x11grab

Yeah, ffmpeg is a very powerful tool, however, I don't think I have the time and motivation to replicate something with such a wide scope, sorry about that.

If someone is interested in doing it, it might be better if the relevant parts of wf-recorder were ported so that ffmpeg has a `wayland_grab` as suggested in #139
